server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://192.168.1.10:3306/SPRING?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: LYP809834049
mybatis:
  mapper-locations: classpath:mapper/*.xml